version: "3.9"
services:
  mongodb:
    image : mongo:latest
    restart: always 
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db    
  api:
    build: .
    ports: 
      - 3000:3000    
    environment:
      PORT : 3000 
      URI :  mongodb://localhost:27017/jasser  
    depends_on:
      - mongodb
        
volumes:
   mongo_db : {}